TOBUILD   := \
             bin/sysv/$(TARGET)/crapchat \
             bin/posix/$(TARGET)/crapchat

CXX       := g++

CXXFLAGS  := \
             -g \
             -fpermissive \
             -Wint-to-pointer-cast \
             $(HDRS) \
             $(DBG_FLAGS)

LDFLAGS   := \
             -lrt \
             -lpthread

all: $(TOBUILD)

run_sysv: all
	./bin/sysv/$(TARGET)/crapchat $(RUN_ARGS)

run_posix: all
	./bin/posix/$(TARGET)/crapchat $(RUN_ARGS)
